[book]
authors = ["lzzsG"]
language = "en"
multilingual = false
src = "src"
title = "os-mdbook-test"


[output.html]
default-theme = "light"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/lzzsG/test-all-to-mdbook"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
